export const barrierBreakdown = [
  {
    id: "geography",
    label: "Geography & Distance",
    percentage: 28,
    color: "#E07A5F",
    description: "Distance to the nearest trial site is the single largest barrier to enrollment.",
  },
  {
    id: "transportation",
    label: "Transportation",
    percentage: 18,
    color: "#E07A5F",
    description: "Lack of a reliable vehicle or inability to afford repeated trips eliminates nearly 1 in 5 drop-offs.",
  },
  {
    id: "work",
    label: "Work Schedule & Lost Wages",
    percentage: 16,
    color: "#E07A5F",
    description: "Weekday-only visit windows and no compensation for missed work disproportionately affect hourly workers.",
  },
  {
    id: "digital",
    label: "Digital Access",
    percentage: 14,
    color: "#E07A5F",
    description: "Complex digital enrollment processes exclude older adults and those without reliable internet or devices.",
  },
  {
    id: "language",
    label: "Language",
    percentage: 13,
    color: "#E07A5F",
    description: "English-only materials create an invisible wall for non-English speaking patients.",
  },
  {
    id: "insurance",
    label: "Insurance & Cost",
    percentage: 11,
    color: "#E07A5F",
    description: "Ancillary costs — parking, childcare, travel — add up quickly and are rarely reimbursed.",
  },
];

export const barrierByDemographic = [
  {
    demographic: "Rural Patients",
    geography: 52,
    transportation: 38,
    work: 14,
    digital: 22,
    language: 8,
    insurance: 18,
  },
  {
    demographic: "Urban Patients",
    geography: 12,
    transportation: 24,
    work: 28,
    digital: 10,
    language: 18,
    insurance: 14,
  },
  {
    demographic: "Patients Over 65",
    geography: 24,
    transportation: 30,
    work: 4,
    digital: 48,
    language: 10,
    insurance: 22,
  },
  {
    demographic: "Patients Under 40",
    geography: 18,
    transportation: 16,
    work: 42,
    digital: 6,
    language: 12,
    insurance: 16,
  },
  {
    demographic: "Income Under $40K",
    geography: 28,
    transportation: 36,
    work: 38,
    digital: 24,
    language: 14,
    insurance: 32,
  },
  {
    demographic: "Income Over $80K",
    geography: 10,
    transportation: 8,
    work: 10,
    digital: 4,
    language: 6,
    insurance: 6,
  },
];